"""events.py - a module to generate events relevant to disease dynamics"""

import numpy as np
import pandas as pd

def init_infect(indvs, n):
    """Create `n` initial infections (i.e. at time 0) within your described population (e.g. individuals generated by
    `unif_indvs`)
    """
    return np.random.choice(indvs.index, size=n, replace=False))

def event_db(n, pop):
    """Create an event database, and with `n` initial infection events, based on a specified population, `pop`."""
    return pd.DataFrame({"time":np.repeat(0, n), 
                         "ind_ID":np.random.choice(pop.index, size=n, replace=False), 
                         "event_type":np.repeat("infection_status",n), 
                         "event_details":np.repeat("i",n)})
    
def omega_s():
    """Susceptibility function - generate a vector of individual specific susceptibility (e.g. related to individual covariates)"""
    
def omega_t():
    """Transmissability function - generate a vector of individual specific transmissability (e.g. related to individual covariates)"""

def kappa():
    """Infection kernel - risk in relation to a measure of seperation of infected and susceptible individuals"""
    
def epsilon():
    """Infection process which describe some other random behaviour (e.g. infections originating from outside influences)"""

def si_model(alpha, beta):
    """SI (susceptible, infected) ILM."""

def sir_model(I_dur, alpha, beta):
    """SIR (susceptible, infected, recovered/removed) ILM where the recovery period is constant"""
    
def seir_model(I_dur, alpha, beta):
    """SEIR (susceptible, exposed, infected, recovered/removed) ILM where the latent (exposed), and recovery period are constant"""