# Main simulation file
# Justin Angevaare
# September 2014

import numpy as np
import pandas as pd

def unif_indvs(n, x, y):
    """Generates `n`, random uniformly distributed individuals over a cartesian study area of size `x` by `y`. In the future alternative distributions may be possible."""
    return pd.DataFrame({'x':np.random.uniform(0, x, n),
                  'y':np.random.uniform(0, y, n)})

def init_infect(indvs, n):
    """Create `n` initial infections (i.e. at time 0) within your described population (e.g. individuals generated by `unif_indvs`)"""
    return np.random.choice(indvs.index, size=n, replace=False)

# Loop population update functions as desired

# Output histories in CSV file
